### ISSUE TITLE
MacOS documentation build hangs

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#1611]
MacOS 10.13.5, Xcode-9.4.1, current Macports-installed python-2.7.15 and python-3.6.5, sphinx, etc.

```
. . . . .
cd . && ln -fs libbotan-2.7.dylib libbotan-2.7.7.0.dylib
clang++ -headerpad_max_install_names -fstack-protector -m64 -pthread -stdlib=libc++ -maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4 -msse4.2 -Os -Ofast -I/opt/local/include  build/obj/cli/asn1.o build/obj/cli/cc_enc.o build/obj/cli/cli.o build/obj/cli/cli_rng.o build/obj/cli/compress.o build/obj/cli/encryption.o build/obj/cli/main.o build/obj/cli/math.o build/obj/cli/psk.o build/obj/cli/pubkey.o build/obj/cli/speed.o build/obj/cli/timing_tests.o build/obj/cli/tls_client.o build/obj/cli/tls_http_server.o build/obj/cli/tls_proxy.o build/obj/cli/tls_server.o build/obj/cli/tls_utils.o build/obj/cli/utils.o build/obj/cli/x509.o -L/opt/local/lib -L. -lbotan-2 -L/opt/local/lib -lboost_filesystem-mt -lboost_system-mt -lbz2 -lcrypto -ldl -llzma -lsqlite3 -lz -framework Security -o botan
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
install_name_tool -change '/opt/local/lib/libbotan-2.7.dylib' '@executable_path/libbotan-2.7.dylib' botan
clang++ -headerpad_max_install_names -fstack-protector -m64 -pthread -stdlib=libc++ -maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4 -msse4.2 -Os -Ofast -I/opt/local/include  build/obj/test/main.o build/obj/test/test_aead.o build/obj/test/test_asn1.o build/obj/test/test_bigint.o build/obj/test/test_block.o build/obj/test/test_c25519.o build/obj/test/test_certstor.o build/obj/test/test_compression.o build/obj/test/test_cryptobox.o build/obj/test/test_datastore.o build/obj/test/test_dh.o build/obj/test/test_dl_group.o build/obj/test/test_dlies.o build/obj/test/test_dsa.o build/obj/test/test_ecc_pointmul.o build/obj/test/test_ecdh.o build/obj/test/test_ecdsa.o build/obj/test/test_ecgdsa.o build/obj/test/test_ecies.o build/obj/test/test_eckcdsa.o build/obj/test/test_ed25519.o build/obj/test/test_elg.o build/obj/test/test_entropy.o build/obj/test/test_ffi.o build/obj/test/test_filters.o build/obj/test/test_fpe.o build/obj/test/test_gf2m.o build/obj/test/test_gost_3410.o build/obj/test/test_hash.o build/obj/test/test_hash_id.o build/obj/test/test_kdf.o build/obj/test/test_keywrap.o build/obj/test/test_mac.o build/obj/test/test_mceliece.o build/obj/test/test_modes.o build/obj/test/test_mp.o build/obj/test/test_name_constraint.o build/obj/test/test_newhope.o build/obj/test/test_ocb.o build/obj/test/test_ocsp.o build/obj/test/test_octetstring.o build/obj/test/test_oid.o build/obj/test/test_os_utils.o build/obj/test/test_otp.o build/obj/test/test_package_transform.o build/obj/test/test_pad.o build/obj/test/test_passhash.o build/obj/test/test_pbkdf.o build/obj/test/test_pem.o build/obj/test/test_pk_pad.o build/obj/test/test_pkcs11.o build/obj/test/test_pkcs11_high_level.o build/obj/test/test_pkcs11_low_level.o build/obj/test/test_psk_db.o build/obj/test/test_pubkey.o build/obj/test/test_rfc6979.o build/obj/test/test_rng.o build/obj/test/test_rng_kat.o build/obj/test/test_rsa.o build/obj/test/test_runner.o build/obj/test/test_simd.o build/obj/test/test_siv.o build/obj/test/test_sm2.o build/obj/test/test_srp6.o build/obj/test/test_stream.o build/obj/test/test_tests.o build/obj/test/test_tls.o build/obj/test/test_tls_messages.o build/obj/test/test_tpm.o build/obj/test/test_tss.o build/obj/test/test_utils.o build/obj/test/test_workfactor.o build/obj/test/test_x509_dn.o build/obj/test/test_x509_path.o build/obj/test/test_xmss.o build/obj/test/tests.o build/obj/test/unit_ecc.o build/obj/test/unit_ecdh.o build/obj/test/unit_ecdsa.o build/obj/test/unit_tls.o build/obj/test/unit_tls_policy.o build/obj/test/unit_x509.o -L/opt/local/lib -L. -lbotan-2 -L/opt/local/lib -lboost_filesystem-mt -lboost_system-mt -lbz2 -lcrypto -ldl -llzma -lsqlite3 -lz -framework Security -o botan-test
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
install_name_tool -change '/opt/local/lib/libbotan-2.7.dylib' '@executable_path/libbotan-2.7.dylib' botan-test

[hangs here, have to kill it with ^C]

^C
Traceback (most recent call last):
  File "src/scripts/build_docs.py", line 225, in <module>
    sys.exit(main())
  File "src/scripts/build_docs.py", line 221, in main
    run_and_check(cmd)
  File "src/scripts/build_docs.py", line 76, in run_and_check
    (stdout, stderr) = proc.communicate()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 483, in communicate
    return self._communicate(input)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1124, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1178, in _communicate_with_poll
    ready = poller.poll()
KeyboardInterrupt
make: *** [build/doc.stamp] Error 1

$
```

**Comment by randombit** [comment]
Try `./src/scripts/build_docs.py --verbose` should show which command is hanging.

**Comment by mouse07410** [comment]
```
$ ./src/scripts/build_docs.py --verbose
  DEBUG: Executing sphinx-build -c ./src/configs/sphinx -j 8 -b html ./doc/manual build/docs/manual
  DEBUG: Running Sphinx v1.7.5
Ignoring ImportError and using old theme
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
no targets are out of date.
build succeeded.

The HTML pages are in build/docs/manual.

  DEBUG: Executing sphinx-build -c ./src/configs/sphinx -j 8 -b latex ./doc/manual /var/folders/c6/lnc_0m093ys8w16md_fm1mnxhtfnj8/T/botan_latex_ac3n5te5
  DEBUG: Running Sphinx v1.7.5
Ignoring ImportError and using old theme
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 41 added, 0 changed, 0 removed
reading sources... [ 11%] abi .. cipher_modes
reading sources... [ 22%] cli .. cryptobox
reading sources... [ 33%] deprecated .. fpe
reading sources... [ 44%] fuzzing .. kdf
reading sources... [ 55%] keywrap .. passhash
reading sources... [ 66%] pbkdf .. python
reading sources... [ 77%] rng .. srp
reading sources... [ 88%] stream_ciphers .. versions
reading sources... [100%] x509

waiting for workers...
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing botan.tex...contents index goals support building versions secmem rng hash block_cipher stream_ciphers message_auth_codes cipher_modes pubkey x509 tls credentials_manager bigint kdf pbkdf keywrap passhash cryptobox srp psk_db filters fpe ecc compression pkcs11 tpm otp ffi python cli side_channels packaging fuzzing deprecated abi roadmap 
resolving references...
writing... done
copying TeX support files...
done
build succeeded, 9 warnings.

The LaTeX files are in ../../../../var/folders/c6/lnc_0m093ys8w16md_fm1mnxhtfnj8/T/botan_latex_ac3n5te5.
Run 'make' in that directory to run these through (pdf)latex
(use `make latexpdf' here to do that automatically).

  DEBUG: /Users/ur20980/src/botan/doc/manual/tls.rst:292: WARNING: Parsing of expression failed. Using fallback parser. Error was:
Error in postfix expression, expected primary expression or type.
If primary expression:
  Invalid definition: Expected identifier in nested name. [error at 332]
    Client( Callbacks& callbacks, Session_Manager& session_manager, Credentials_Manager& creds, const Policy& policy, RandomNumberGenerator& rng, const Server_Information& server_info = Server_Information(), const Protocol_Version offer_version = Protocol_Version::latest_tls_version(), const std::vector<std::string>& next_protocols = {}, size_t reserved_io_buffer_size = 16*1024 )
    --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
If type:
  Invalid definition: Expected identifier in nested name. [error at 332]
    Client( Callbacks& callbacks, Session_Manager& session_manager, Credentials_Manager& creds, const Policy& policy, RandomNumberGenerator& rng, const Server_Information& server_info = Server_Information(), const Protocol_Version offer_version = Protocol_Version::latest_tls_version(), const std::vector<std::string>& next_protocols = {}, size_t reserved_io_buffer_size = 16*1024 )
    --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
/Users/ur20980/src/botan/doc/manual/x509.rst:453: WARNING: Parsing of expression failed. Using fallback parser. Error was:
Error in postfix expression, expected primary expression or type.
If primary expression:
  Invalid definition: Expected identifier in nested name. [error at 467]
    Path_Validation_Result x509_path_validate(const X509_Certificate& end_cert, const Path_Validation_Restrictions& restrictions, const Certificate_Store& store, const std::string& hostname = "", Usage_Type usage = Usage_Type::UNSPECIFIED, std::chrono::system_clock::time_point validation_time = std::chrono::system_clock::now(), std::chrono::milliseconds ocsp_timeout = std::chrono::milliseconds(0), const std::vector<std::shared_ptr<const OCSP::Response>>& ocsp_resp = {})
    -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
If type:
  Invalid definition: Expected identifier in nested name. [error at 467]
    Path_Validation_Result x509_path_validate(const X509_Certificate& end_cert, const Path_Validation_Restrictions& restrictions, const Certificate_Store& store, const std::string& hostname = "", Usage_Type usage = Usage_Type::UNSPECIFIED, std::chrono::system_clock::time_point validation_time = std::chrono::system_clock::now(), std::chrono::milliseconds ocsp_timeout = std::chrono::milliseconds(0), const std::vector<std::shared_ptr<const OCSP::Response>>& ocsp_resp = {})
    -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
/Users/ur20980/src/botan/doc/manual/x509.rst:827: WARNING: Parsing of expression failed. Using fallback parser. Error was:
Error in postfix expression, expected primary expression or type.
If primary expression:
  Invalid definition: Expected identifier in nested name. [error at 195]
    Certificate_Status_Code check_signature(                const std::vector<Certificate_Store*>& trust_roots,                const std::vector<std::shared_ptr<const X509_Certificate>>& cert_path = {}) const
    ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
If type:
  Invalid definition: Expected identifier in nested name. [error at 195]
    Certificate_Status_Code check_signature(                const std::vector<Certificate_Store*>& trust_roots,                const std::vector<std::shared_ptr<const X509_Certificate>>& cert_path = {}) const
    ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
/Users/ur20980/src/botan/doc/manual/pkcs11.rst:351: WARNING: Duplicate declaration.
/Users/ur20980/src/botan/doc/manual/pkcs11.rst:1381: WARNING: Footnote [1] is not referenced.
/Users/ur20980/src/botan/doc/manual/pkcs11.rst:269: WARNING: cpp:function targets a functionParam (initialize::label).
/Users/ur20980/src/botan/doc/manual/cli.rst:192: WARNING: Could not lex literal_block as "cpp". Highlighting skipped.
/Users/ur20980/src/botan/doc/manual/cli.rst:197: WARNING: Could not lex literal_block as "cpp". Highlighting skipped.
/Users/ur20980/src/botan/doc/manual/cli.rst:203: WARNING: Could not lex literal_block as "cpp". Highlighting skipped.

  DEBUG: Executing make -C /var/folders/c6/lnc_0m093ys8w16md_fm1mnxhtfnj8/T/botan_latex_ac3n5te5

```
this is where it seems to be stuck...

**Comment by randombit** [comment]
Some problem with TeX maybe?

Try killing the script when it reaches that point, then execute the same `make` command directly, see what happens.

**Comment by mouse07410** [comment]
In case it matters:
```
cat /var/folders/c6/lnc_0m093ys8w16md_fm1mnxhtfnj8/T/botan_latex_ac3n5te5/Makefile
# Makefile for Sphinx LaTeX output

ALLDOCS = $(basename $(wildcard *.tex))
ALLPDF = $(addsuffix .pdf,$(ALLDOCS))
ALLDVI = $(addsuffix .dvi,$(ALLDOCS))
ALLXDV =
ALLPS  = $(addsuffix .ps,$(ALLDOCS))
ALLIMGS = $(wildcard *.png *.gif *.jpg *.jpeg)

# Prefix for archive names
ARCHIVEPREFIX =
# Additional LaTeX options (passed via variables in latexmkrc/latexmkjarc file)
export LATEXOPTS =
# Additional latexmk options
LATEXMKOPTS =
# format: pdf or dvi (used only by archive targets)
FMT = pdf

LATEX = latexmk -dvi
PDFLATEX = latexmk -pdf -dvi- -ps-


%.png %.gif %.jpg %.jpeg: FORCE_MAKE
	extractbb '$@'

%.dvi: %.tex FORCE_MAKE
	$(LATEX) $(LATEXMKOPTS) '$<'

%.ps: %.dvi
	dvips '$<'

%.pdf: %.tex FORCE_MAKE
	$(PDFLATEX) $(LATEXMKOPTS) '$<'

all: $(ALLPDF)

all-dvi: $(ALLDVI)

all-ps: $(ALLPS)

all-pdf: $(ALLPDF)

zip: all-$(FMT)
	mkdir $(ARCHIVEPREFIX)docs-$(FMT)
	cp $(ALLPDF) $(ARCHIVEPREFIX)docs-$(FMT)
	zip -q -r -9 $(ARCHIVEPREFIX)docs-$(FMT).zip $(ARCHIVEPREFIX)docs-$(FMT)
	rm -r $(ARCHIVEPREFIX)docs-$(FMT)

tar: all-$(FMT)
	mkdir $(ARCHIVEPREFIX)docs-$(FMT)
	cp $(ALLPDF) $(ARCHIVEPREFIX)docs-$(FMT)
	tar cf $(ARCHIVEPREFIX)docs-$(FMT).tar $(ARCHIVEPREFIX)docs-$(FMT)
	rm -r $(ARCHIVEPREFIX)docs-$(FMT)

gz: tar
	gzip -9 < $(ARCHIVEPREFIX)docs-$(FMT).tar > $(ARCHIVEPREFIX)docs-$(FMT).tar.gz

bz2: tar
	bzip2 -9 -k $(ARCHIVEPREFIX)docs-$(FMT).tar

xz: tar
	xz -9 -k $(ARCHIVEPREFIX)docs-$(FMT).tar

clean:
	rm -f *.log *.ind *.aux *.toc *.syn *.idx *.out *.ilg *.pla *.ps *.tar *.tar.gz *.tar.bz2 *.tar.xz $(ALLPDF) $(ALLDVI) $(ALLXDV) *.fls *.fdb_latexmk

.PHONY: all all-pdf all-dvi all-ps clean zip tar gz bz2 xz
.PHONY: FORCE_MAKE$     [i.e., Makefile does not end with <CR><LF>]
```

**Comment by mouse07410** [comment]
> Some problem with TeX maybe?

Not sure. This is `texlive-2018`, recently installed - therefore a potential suspect...

> Try killing the script when it reaches that point, then execute the same make command directly, see what happens.

```
$ make -C /var/folders/c6/lnc_0m093ys8w16md_fm1mnxhtfnj8/T/botan_latex_ac3n5te5
latexmk -pdf -dvi- -ps-  'botan.tex'
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex   -recorder  "botan.tex"'
------------
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018/MacPorts 2018.47642_0) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./botan.tex
LaTeX2e <2018-04-01> patch level 2
Babel <3.18> and hyphenation patterns for 46 language(s) loaded.
(./sphinxmanual.cls
Document Class: sphinxmanual 2017/03/26 v1.6 Document class (Sphinx manual)
(/opt/local/share/texmf-texlive/tex/latex/base/report.cls
Document Class: report 2014/09/29 v1.4h Standard LaTeX document class
(/opt/local/share/texmf-texlive/tex/latex/base/size10.clo)))
(/opt/local/share/texmf-texlive/tex/latex/base/inputenc.sty)
(/opt/local/share/texmf-texlive/tex/latex/cmap/cmap.sty)
(/opt/local/share/texmf-texlive/tex/latex/base/fontenc.sty
(/opt/local/share/texmf-texlive/tex/latex/base/t1enc.def)<<t1.cmap>>)
(/opt/local/share/texmf-texlive/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/opt/local/share/texmf-texlive/tex/latex/amsmath/amstext.sty
(/opt/local/share/texmf-texlive/tex/latex/amsmath/amsgen.sty))
(/opt/local/share/texmf-texlive/tex/latex/amsmath/amsbsy.sty)
(/opt/local/share/texmf-texlive/tex/latex/amsmath/amsopn.sty))
(/opt/local/share/texmf-texlive/tex/latex/amsfonts/amssymb.sty
(/opt/local/share/texmf-texlive/tex/latex/amsfonts/amsfonts.sty))
(/opt/local/share/texmf-texlive/tex/generic/babel/babel.sty
(/opt/local/share/texmf-texlive/tex/generic/babel/switch.def)
(/opt/local/share/texmf-texlive/tex/generic/babel-english/english.ldf
(/opt/local/share/texmf-texlive/tex/generic/babel/babel.def
(/opt/local/share/texmf-texlive/tex/generic/babel/txtbabel.def))))
(/opt/local/share/texmf-texlive/tex/latex/psnfss/times.sty)

! LaTeX Error: File `fncychap.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
```

**Comment by randombit** [comment]
> ! LaTeX Error: File `fncychap.sty' not found.

Well, seems like a Sphinx or TexLive issue then. FWIW TexLive 2018.47465 works fine for me on Linux for this.

We can pass additional arguments to pdflatex via make variables, but I can't find any way to make `pdflatex` error out when it can't find a file rather than asking the user.

**Comment by mouse07410** [comment]
The current TeXLive 2018 works fine on several other MacOS machines here with Botan documentation in PDF. You're probably right, it's likely to be an issue with my TeXlive installation on that machine (though why that machine falls out of the herd, I've no idea).

Let me close this one for now, and re-open if it turns out to be Botan-related.

Thanks!
