### ISSUE TITLE
ECDSA test crashes when compiled with XLC 16 on ppc64le

### ISSUE THREAD

**Issue by randombit** [randombit/botan#1802]
Crash occurs with -O1 or -O2, in `ecdsa_unit` calling test `test_read_pkcs8`. Other tests that load ECDSA PEM files (like `test_ecc_key_with_rfc5915_extensions`) run ok.

```
$ xlc --version
IBM XL C/C++ for Linux, V16.1.1 (Community Edition)
Version: 16.01.0001.0000
```

```
#0  Botan::ECDSA_PrivateKey::ECDSA_PrivateKey (this=0xe0, alg_id=..., key_bits=std::vector of length 140737212302512, capacity 140737212302776 = {...})
    at build/include/botan/pk_keys.h:177
#1  0x00007ffff77883f8 in Botan::load_private_key (alg_id=..., key_bits=<error reading variable: Cannot access memory at address 0x8>) at src/lib/pubkey/pk_algs.cpp:186
#2  0x00007ffff77a1e7c in Botan::PKCS8::(anonymous namespace)::load_key(Botan::DataSource&, std::function<std::string ()>, bool) (source=..., get_pass=..., is_encrypted=128)
    at src/lib/pubkey/pkcs8.cpp:345
#3  0x00007ffff77a3230 in load_key (source=...) at src/lib/pubkey/pkcs8.cpp:377
Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
#4  Botan::PKCS8::load_key (fsname=, rng=...) at src/lib/pubkey/pkcs8.cpp:455
#5  0x000000001049b3e4 in Botan_Tests::(anonymous namespace)::test_read_pkcs8 () at /usr/lib/gcc/ppc64le-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/basic_string.h:490
#6  0x000000001049a2a0 in Botan_Tests::(anonymous namespace)::ECDSA_Unit_Tests::run (this=0x7ffff7ff5608) at src/tests/unit_ecdsa.cpp:441
#7  0x000000001038f028 in Botan_Tests::Test_Runner::run_tests (this=0x1, tests_to_run=warning: Type size unknown, assuming 1. Try casting to a known type, or void *.
<error reading variable: Cannot access memory at address 0x9>, test_run=0, tot_test_runs=1)
    at src/tests/test_runner.cpp:263
#8  0x000000001038c544 in Botan_Tests::Test_Runner::run (this=0x1, opts=...) at src/tests/test_runner.cpp:199
#9  0x0000000010084584 in main (argc=119, argv=0x1f) at src/tests/main.cpp:101
```

In one frame, the algorithm id looks ok, but in the next down it is junk

```
(gdb) print alg_id
$3 = {<Botan::ASN1_Object> = {__vfp = 0x7ffff7e45340 <vtable for Botan::AlgorithmIdentifier+16>}, __vfp = 0x7ffff7e45340 <vtable for Botan::AlgorithmIdentifier+16>, 
  oid = {<Botan::ASN1_Object> = {__vfp = 0x7ffff7e46440 <vtable for Botan::OID+16>}, __vfp = 0x7ffff7e46440 <vtable for Botan::OID+16>, 
    m_id = std::vector of length 6, capacity 8 = {1, 2, 840, 10045, 2, 1}}, parameters = std::vector of length 15, capacity 16 = {6 '\006', 13 '\r', 43 '+', 6 '\006', 1 '\001', 
    4 '\004', 1 '\001', 192 '\300', 109 'm', 3 '\003', 1 '\001', 2 '\002', 9 '\t', 0 '\000', 33 '!'}}
(gdb) down
#1  0x00007ffff77883f8 in Botan::load_private_key (alg_id=..., key_bits=<error reading variable: Cannot access memory at address 0x8>) at src/lib/pubkey/pk_algs.cpp:186
186           return std::unique_ptr<Private_Key>(new ECDSA_PrivateKey(alg_id, key_bits));
(gdb) print alg_id
$4 = (const Botan::AlgorithmIdentifier &) @0x7ffff7e45340: warning: can't find linker symbol for virtual table for `Botan::AlgorithmIdentifier' value
warning:   found `Botan::operator!=(Botan::AlgorithmIdentifier const&, Botan::AlgorithmIdentifier const&)' instead
{<Botan::ASN1_Object> = {__vfp = 0x7ffff71e8d10 <Botan::AlgorithmIdentifier::encode_into(Botan::DER_Encoder&) const>}, 
  __vfp = 0x7ffff71e8d10 <Botan::AlgorithmIdentifier::encode_into(Botan::DER_Encoder&) const>, oid = warning: can't find linker symbol for virtual table for `Botan::OID' value
warning:   found `Botan::AlgorithmIdentifier::encode_into(Botan::DER_Encoder&) const' instead
{<Botan::ASN1_Object> = {
      __vfp = 0x7ffff71e8de0 <Botan::AlgorithmIdentifier::decode_from(Botan::BER_Decoder&)>}, __vfp = 0x7ffff71e8de0 <Botan::AlgorithmIdentifier::decode_from(Botan::BER_Decoder&)>, 
    m_id = std::vector of length 35184267493052, capacity 890472876934488479 = {1010831461, 943892224, 4162977745, 2080899750, 4160815168, 4225826856, 2088704888, 1610612736, 
      3898774776, 939720720, 3900637224, 4162781184, 740491264, 1082261616, 1610612736, 3900871936, 3900637200, 939786256, 740491264, 4162781192, 1099038772, 1274623677, 
      3896573976, 1013055489, 946058784, 939720720, 4162781192, 4162781184, 3957391400, 3892379712, 941686832, 2080900006, 1317011488, 1013055489, 946058784, 939720720, 4162781192, 
      4162781184, 3957391400, 941686832, 1317011488, 1274623597, 3896573976, 1610612736, 3900871936, 3900637200, 939786256, 740491264, 4162781192, 1082326928, 1013055489, 
      946058784, 3892379712, 2080900006, 939720720, 4162781192, 4162781184, 1275068340, 0, 1092618496, 65920, 0, 232, 1516175394, 1866609998, 829317492, 1735147833, 1953067631, 
      1682533736, 1769238117, 1919248742, 1984246084, 1010831461, 943892224, 4162977761, 2080899750, 4160815152, 3898802176, 740491264, 1082261516, 941686816, 1317011488, 
      1274623433, 3896573976, 3892379696, 941686816, 2080900006, 1317011488, 0, 1092618496, 65664, 0, 64, 1516175384, 913593166, 1952671094, 1749643887, 1749639507, 843334981, 
      30277, 1010831461, 943892224, 1015152641, 948221472, 939786256, 4160946176, 1317011488, 0, 1075841280, 131072, 0, 28, 1516175390, 1866609998, 829317492, 1314079025, 
      1649368881, 1952671082, 1380266563, 1597002571, 1010831461, 943892224, 4162977697, 2080899750, 4160815216, 4225826904, 4223729744, 2088704888, 1013055489, 946039456, 
      1017249793, 950384160, 4225826880, 2090738552, 1610612736, 3900871928, 1610612736, 3905066240, 939524096, 946013696, 2415984688, 4167106616, 2415984712, 939851792, 946077712, 
      4162781184, 947912706, 950403088, 4169072640, 4162781192, 2558591024, 4173266952, 947847184, 949878800, 1207959697, 1610612736, 939524099, 947847208, 2550202416, 949878824, 
      1274708905, 1610612736, 2145647480, 3955294288, 3892379760, 3957391448, 2080900006, 941686880, 1317011488, 0, 1093142784, 131712, 0, 196, 1, 48, 1516175398, 1866609998, 
      829317492, 1735147833, 1953067631, 1682533736, 1769238117, 1919248742, 1380266563, 1597002571, 0, 0, 1010831461, 943892224, 4162977665, 2080899750, 4160815248, 4225826936, 
      4223729776, 4221632616, 4167106640, 2088573816, 2090804088, 3898867720...}}, parameters = std::vector of length -7083985105943780295, capacity -7083985404249194801 = {
    <error reading variable>
```

**Comment by randombit** [comment]
Closing because who cares about XLC
