### ISSUE TITLE
Current master hangs in configure.py

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#1876]
MacOS Mojave 10.14.3, Xcode-10.2, 2.9 GHz Intel Core i7, current Botan master

```
$ python --version
Python 2.7.16
$ ./configure.py --prefix=/opt/local --with-commoncrypto --with-os-features=security_framework,commoncrypto,getentropy --with-openssl --with-lzma --with-bzip2 --with-zlib --with-sqlite3 --with-python-version=2.7 --with-sphinx --with-pdf --cc-abi-flags='-maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4 -msse4.2 -Os -Ofast -I/opt/local/include' 2>&1 | tee conf-out.txt
   INFO: Configuring to build Botan 2.11.0 (revision git:f53307907b97d4de90f2129eefcf696402cf3a1b)
   INFO: ./configure.py invoked with options "--prefix=/opt/local --with-commoncrypto --with-os-features=security_framework,commoncrypto,getentropy --with-openssl --with-lzma --with-bzip2 --with-zlib --with-sqlite3 --with-python-version=2.7 --with-sphinx --with-pdf --cc-abi-flags=-maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4 -msse4.2 -Os -Ofast -I/opt/local/include"
   INFO: Autodetected platform information: OS="Darwin" machine="x86_64" proc="i386"
   INFO: Guessing target OS is darwin (use --os to set)
   INFO: Guessing target processor is a x86_64 (use --cpu to set)
^C

```

Removing some options from the config did not help:
```
$ ./configure.py --prefix=/opt/local --with-openssl --with-lzma --with-bzip2 --with-zlib --with-sqlite3 --with-python-version=2.7 --with-sphinx --with-pdf --cc-abi-flags='-maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4 -msse4.2 -Os -Ofast -I/opt/local/include'
   INFO: Configuring to build Botan 2.11.0 (revision git:f53307907b97d4de90f2129eefcf696402cf3a1b)
   INFO: ./configure.py invoked with options "--prefix=/opt/local --with-openssl --with-lzma --with-bzip2 --with-zlib --with-sqlite3 --with-python-version=2.7 --with-sphinx --with-pdf --cc-abi-flags=-maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4 -msse4.2 -Os -Ofast -I/opt/local/include"
   INFO: Autodetected platform information: OS="Darwin" machine="x86_64" proc="i386"
   INFO: Guessing target OS is darwin (use --os to set)
   INFO: Guessing target processor is a x86_64 (use --cpu to set)
^CTraceback (most recent call last):
  File "./configure.py", line 3241, in <module>
    sys.exit(main(argv=sys.argv))
  File "./configure.py", line 3214, in main
    cc_min_version = options.cc_min_version or calculate_cc_min_version(options, cc, source_paths)
  File "./configure.py", line 2994, in calculate_cc_min_version
    cc_output = run_compiler_preproc(options, ccinfo, detect_version_source, "0.0")
  File "./configure.py", line 2967, in run_compiler_preproc
    universal_newlines=True).communicate()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 483, in communicate
    return self._communicate(input)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1124, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1178, in _communicate_with_poll
    ready = poller.poll()
KeyboardInterrupt
$ 
```

**Comment by randombit** [comment]
It looks like we ask the compiler for its version, and it hangs. Try `--verbose`.

**Comment by mouse07410** [comment]
Looks like something was broken on my machine (99.9% probability - related to Xcode-10.2 upgrade).

Thankfully, it doesn't replicate - so let me close this. *Will reopen if it strikes again, which I hope won't happen.*
