### ISSUE TITLE
Coverity scan is broken

### ISSUE THREAD

**Issue by randombit** [randombit/botan#1920]
Worked on March 29th (last build). Now fails. Logs don't really give a clue what is going on beyond curl being unhappy with (some) certificate. https://travis-ci.org/randombit/botan/builds/525719515

```
Coverity Scan analysis selected for branch coverity_scan.
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html
curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
/home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at '' (JSON::ParserError)
	from /home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/json/common.rb:156:in `parse'
	from /home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/json/common.rb:15:in `[]'
	from -e:1:in `<main>'
/home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected tok
```

**Comment by randombit** [comment]
https://travis-ci.community/t/certificate-issue-during-coverity-build/3153/5

**Comment by randombit** [comment]
Is a problem with Coverity upstream, not Travis or our config. They will fix it eventually (hopefully).
