### ISSUE TITLE
Why is botan.py using python2 explicitly

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#305]
Is there any reason botan.py uses Python 2 explicitly?

I recently contacted the maintainer on Arch Linux, where they use Python 3 by default and told him that Botan does not need an explicit python2 dependency, so he could [get rid of a lot of code](https://projects.archlinux.org/svntogit/community.git/commit/trunk?h=packages/botan&id=652a2dd341a781452c450f2f106439ca8b1c3a27). Then he found the header `#!/usr/bin/env python2` in `/usr/lib/python3.5/site-packages/botan.py`

Can we change that to `#!/usr/bin/env python`?

**Comment by mouse07410** [comment]
I have ported botan.py to work with both python2 and python3. But I see some python2 dependencies been introduced in that file since (e.g. like 747)? 

Let me review and re-work botan.py, and post a PR.

**Comment by mouse07410** [comment]
I'm having problems porting McEliece stuff to Python3. Might take some time for me to get it right. I don't think `botan.py` would run under Python3 as is.

**Comment by randombit** [comment]
With 514474b9 all of botan.py works in python2 and python3 again and the file header has been changed.

The changes python3 needs for ctypes are wrapped in a couple of functions now so breakage should be less likely as ffi continues to be extended. Checking that botan.py runs under python2 and/or python3 during CI would be a step forward here.

**Comment by mouse07410** [comment]
Yes, your way is much better.

But my comment in this commit stands: there's a problem with the `botan_api_rev` comparison. Here's what I get form the fresh Github pull and clean install:

```
Tests all ok
$ sudo make install
Password:
sphinx-build -c ./src/build-data/sphinx -b latex ./doc/manual build/docs/manual
Running Sphinx v1.3.1
WARNING: the config value 'latex_show_urls' has type `bool', defaults to `str.'
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
processing botan.tex... contents index building python firststep secmem rng filters pubkey mceliece x509 ocsp tls credentials_manager aead bigint lowlevel kdf pbkdf passhash cryptobox srp fpe compression versions ffi 
resolving references...
writing... done
copying TeX support files...
done
build succeeded, 1 warning.
./src/scripts/install.py --destdir=/opt/local --build-dir="build" --bindir=bin --libdir=lib --docdir=doc --includedir=include
   INFO: Botan 1.11.22 installation complete
$ python3 src/python/botan.py 
Traceback (most recent call last):
  File "src/python/botan.py", line 29, in <module>
    raise Exception("Bad botan API rev got %d expected %d" % (botan_api_rev, expected_api_rev))
Exception: Bad botan API rev got 20151001 expected 20151015
```

**Comment by mouse07410** [comment]
Your change is definitely a better way. I've polished its output a bit, and opened a new PR #308

**Comment by randombit** [comment]
@mouse07410 I think you need to recompile (you can shortcut with `configure.py --dirty` followed by `rm build/obj/lib/ffi.o` and `make`) to pick up the updated version code in the library itself.

The comparison should stay equality rather than less than - just because the version of the FFI API the botan.py is running against came out later does not mean it will support all APIs that existed in the release in question. Eg I have no particular reason to believe that you could take this 20151015 botan.py and run it against say a future FFI (says 20170303) and expect it to work. Rather than allowing something which we cannot guarantee will work and certainly cannot fix retroactively, we tie it to the version of the API which was included in that shipping library. The version numbers are just monotonically increasing version codes - think of them as individual major numbers.

There are other options available - we could have botan.py ignore the version code and probe for function signatures using ctypes, or have it maintain a map of API codes to supported APIs - but just asserting that this botan.py will work against arbitrary unknown future versions of the library certainly isn't viable, at least while the C89 API is still in such an early stage.

Later on when the API churn here has dropped off, either changing the semantics of the version to match your expectation or adding some system of minor numbers to indicate new features which are forward but not backward compatible with older releases may well make sense so binding wrappers are less tied to individual versions.

**Comment by mouse07410** [comment]
> The comparison should stay equality rather than less than - just because the version of the
> FFI API the botan.py is running against came out later does not mean it will support all APIs
> that existed in the release in question........just asserting that this botan.py will work against
> arbitrary unknown future versions of the library certainly isn't viable, at least while the C89 API
> is still in such an early stage..........Later on when the API churn here has dropped off, either
> changing the semantics of the version to match your expectation or adding some system of minor
> numbers to indicate new features which are forward but not backward compatible with older
> releases may well make sense so binding wrappers are less tied to individual versions.

Yes, I see your point. Let's do as you say.

Could we agree on the rest of the changes PR #308 brings? Should I update it, removing the version comparison change?

**Comment by webmaster128** [comment]
There is an issue left using Python 3.2.3:

```
Botan 1.11.22 (unreleased, revision git:1e904a14f0ef786d5c79d3772a0ae43a07f80a3d, distribution unspecified)
v1.11.22
Traceback (most recent call last):
  File "src/python/botan.py", line 854, in <module>
    sys.exit(main())
  File "src/python/botan.py", line 851, in main
    test()
  File "src/python/botan.py", line 836, in test
    test_kdf()
  File "src/python/botan.py", line 650, in test_kdf
    hex_encode(kdf('KDF2(SHA-1)', hex_decode('701F3480DFE95F57941F804B1B2413EF'), 7,
  File "src/python/botan.py", line 83, in hex_decode
    return unhexlify(buf)
TypeError: 'str' does not support the buffer interface
```

**Comment by mouse07410** [comment]
It is strange:
```
$ python3 --version
Python 3.4.3
$ python3 src/python/botan.py 

Botan 1.11.22 (unreleased, revision git:514474b98ccdfa6c0f76576c0ebfbec2af637d81, distribution unspecified)
v1.11.22

KDF2(SHA-1)   fbecb3ccfeec6e
PBKDF2(SHA-1) 59b2b1143b4cb1059ec58d9722fb1c72471e0d85c6f7543ba5228526375b0127
good output   59B2B1143B4CB1059EC58D9722FB1C72471E0D85C6F7543BA5228526375B0127

PBKDF2(SHA-256) x=timed, y=iterated; salt = 5b7666974f488621f9b39f57 (len=12)  #iterations = 220000

x b41a02bdf6990942778359582b96ad87bdb96f201719585ac1319a1ed65191bc
y b41a02bdf6990942778359582b96ad87bdb96f201719585ac1319a1ed65191bc

HMAC output correct: a21b1f5d4cf4f73a4dd939750f7a066a7f98cc131cb16a6692759021cfab8181

rng output:
	c925e276e2faa3d76f25a5ff00adf82541abc6acf810d296ad53f3f32ac38f16a3d0d8f94f211272ac1a
	3f28e9f2b37d46b11c4a674900
	b56047ae10d26c43db

md5 hash: 49f68a5c8493ec2c0bf489821c21fc3b (49f68a5c8493ec2c0bf489821c21fc3b)

md5 hash: 47efd2be302a937775e93dea281b6751 (47efd2be302a937775e93dea281b6751)

AES-128/CTR-BE: default nonce=0 update_size=64 key_min=16 key_max=16
  plaintext 82d219eaa98c192fd2f1410c5a91d9867dc837b680 21
  ciphertext 15d7f11029a1f539f4e8b1672de65b07fc0f7986ba 21
  decrypted 82d219eaa98c192fd2f1410c5a91d9867dc837b680 21

Serpent/GCM: default nonce=12 update_size=16 key_min=16 key_max=32
  plaintext 863c9063d1ed6796744a6ee22c0231379765ec93fa 21
  ciphertext 476517fa0405a435dc524a64f2d60e15799fcec695da35f4a30409aab69ffe4a13e84c330a 37
  decrypted 863c9063d1ed6796744a6ee22c0231379765ec93fa 21

ChaCha20Poly1305: default nonce=12 update_size=64 key_min=32 key_max=32
  plaintext 5706adb4a6d5cd99ceaef2f7a0335f65052a0cbfb3 21
  ciphertext cffc692d6fb4ecc410ff22af5afa8690c3f28998159ff7f732e8ada8ef1d5a49ec45212203 37
  decrypted 5706adb4a6d5cd99ceaef2f7a0335f65052a0cbfb3 21

mce 13 411
mce_pub McEliece/SHA-1 fingerprint: 6d5b4c824e2254d2c3c14e47632553280dc12aae (estimated strength 128) (len 200332)
rsapub RSA SHA-1 fingerprint: cc64784b375ac66888db33f61e7cf66c55ade31f estimated strength 102 len 226
Padding is  EME1(SHA-256)
ptext  '28683a060bf37f971b4f4ea7235391b5e1683166a81e4bc8f56e3bce7767d57a'
ctext   '5e16fd5eba90701a66a91e409300668ab1db4cfd45abbda628847bd81c1be51b68ddd9346c88fbe61b3194d2ff96ace81141a6a834ffe881408efe4884cc64d0d3411ee878233e9d53c000c2797e9c8841403ceefae737bcac2a865129b4c1f1f98457835d6fad04412a4abe8ecc1ad0f6beb1ceb47bc4e172d6ab7e396be2bac8b335fdcaa3429b4936ab1864c77a70ff65c2ce6be47353ed6f22840aae424566e22b26b7cca284202752a1e07ce8386eebe85538855512b2e1e159fe236627'
decrypt '28683a060bf37f971b4f4ea7235391b5e1683166a81e4bc8f56e3bce7767d57a'

EMSA4(SHA-384) signature: 63362076deaeaa4f1ed8383c18bf7fe5716e4aff16dc2b1610268f2611f75354596e1d4b5b3cc4efd21776fb00b86fc439aa06943c07ac9f69a757843786c53bd74d386a2dd1514a2d44f05bb589dec7585c93ca3f3ca4eb65606c1670a628ded4661972285c23bd7c6b4fb559ce09458786798cb883354d278903ec95135528561879fea126e04befd43a9b5a608cb1c6c74c49011a94e4f9db5757e33f6e7553aba41792d98533321c3038dd389edb5a112fc350a12c48c4fa5c374b9133c2
good sig accepted? True
bad sig accepted? False
good sig accepted? True

ecdh secp256r1 pubs:
  0469fad4469a1e3124c5eb29826adc7c10b1d12001b4a9136ae15aa3c78895376b675f8d474778e69b6ee8d780e70c11ec17f76190eb40dc66bec522c9ddf1ee21 (salt 4eafca8adcbf44c4)
  04c8855635d43ecc7a3f1467eb1a8bb042477e68fc3433d95f0183d6599ee3ae70a73d5176ef1cf0c521f86bed79b24e87ec40e149584130449ee46e0132d50903 (salt 179f338bf0289566)

ecdh secp256r1 shared:
  45b331ea81504e5b6fdc594df7830fdb4fdf29855f607556e67999bdb04a43eb
  45b331ea81504e5b6fdc594df7830fdb4fdf29855f607556e67999bdb04a43eb

ecdh curve25519 pubs:
  222df85014083bbad92f86272502987a353d09cb0b40202ac33aa498236f0a46 (salt 858d07d1a63d690f)
  d2c3a63f68477fd92a29f19bc306c8fe55bce03f0cefa4206bf48eeb6e3c1773 (salt a8adff66733365b4)

ecdh curve25519 shared:
  ddb5c7a4798c58282b9d5cfa41360b6399a9bd0f433540932a3239048e0d9ff2
  ddb5c7a4798c58282b9d5cfa41360b6399a9bd0f433540932a3239048e0d9ff2

32:42:1C:C3:EC:54:D7:E9:43:EC:51:F0:19:23:BD:85:1D:F2:1B:B9
32:42:1C:C3:EC:54:D7:E9:43:EC:51:F0:19:23:BD:85:1D:F2:1B:B9
070719152718Z
280119151800Z
01
0096452de588f966c4ccdf161dd1f3f5341b71e7
0096452de588f966c4ccdf161dd1f3f5341b71e7
3081d406072a8648ce3d02013081c8020101302806072a8648ce3d0101021d00d7c134aa264366862a18302575d1d787b09f075797da89f57ec8c0ff303c041c68a5e62ca9ce6c1c299803a6c1530b514e182ad8b0042a59cad29f43041c2580f63ccfe44138870713b1a92369e33e2135d266dbb372386c400b0439040d9029ad2c7e5cf4340823b2a87dc68c9e4ce3174c1e6efdee12c07d58aa56f772c0726f24c6b89e4ecdac24354b9e99caa3f6d3761402cd021d00d7c134aa264366862a18302575d0fb98d116bc4b6ddebca3a5a7939f020101033a000401364a4b0f0102e9502ab9dc6855d90b065a6f5e5e48395f8309d57c11abaff21756607ef6757ec9886ca222d83ca04b1a99fa43c5a9bce1
Subject Name: csca-germany
Subject Email: csca-germany@bsi.bund.de
Subject Organization: bund
Subject Organizational Unit: bsi
Subject Country: DE
Subject URI: fax:+492289582722
Issuer Name: csca-germany
Issuer Organization: bund
Issuer Organizational Unit: bsi
Issuer Country: DE
Version: 3
Not valid before: 070719152718Z
Not valid after: 280119151800Z
Constraints:
   Cert Sign
   CRL Sign
Policies: 
   
Signature algorithm: ECDSA/EMSA1(SHA-224)
Serial number: 01
Authority keyid: 0096452DE588F966C4CCDF161DD1F3F5341B71E7
Subject keyid: 0096452DE588F966C4CCDF161DD1F3F5341B71E7
Public Key:
-----BEGIN PUBLIC KEY-----
MIH3MIHUBgcqhkjOPQIBMIHIAgEBMCgGByqGSM49AQECHQDXwTSqJkNmhioYMCV1
0deHsJ8HV5faifV+yMD/MDwEHGil5iypzmwcKZgDpsFTC1FOGCrYsAQqWcrSn0ME
HCWA9jzP5EE4hwcTsakjaeM+ITXSZtuzcjhsQAsEOQQNkCmtLH5c9DQII7KofcaM
nkzjF0webv3uEsB9WKpW93LAcm8kxrieTs2sJDVLnpnKo/bTdhQCzQIdANfBNKom
Q2aGKhgwJXXQ+5jRFrxLbd68o6Wnk58CAQEDHgADATZKSw8BAulQKrncaFXZCwZa
b15eSDlfgwnVfA==
-----END PUBLIC KEY-----
```

Let me investigate.

**Comment by mouse07410** [comment]
One potential fix - and I cannot test it, because it works on my "pythons" fine as is - would be to change the offending lines 649-651 from
```
        print("KDF2(SHA-1)   %s" %
              hex_encode(kdf('KDF2(SHA-1)', hex_decode('701F3480DFE95F57941F804B1B2413EF'), 7,
                             hex_decode('55A4E9DD5F4CA2EF82'))))

```
to
```
        print("KDF2(SHA-1)   %s" %
              hex_encode(kdf('KDF2(SHA-1)', hex_decode(u'701F3480DFE95F57941F804B1B2413EF'), 7,
                             hex_decode(u'55A4E9DD5F4CA2EF82'))))
```
and see if it addresses the problem on your Python-3.2.3. 

If it does - I (or Jack) can make this change throughout the entire file. Though it does not seem needed on either Jack's or my Python3, so I rather suspect an issue with the Python-3.2.3 installation.

FWIW:
```
$ python2 --version
Python 2.7.10
$ python3 --version
Python 3.4.3
```

**Comment by randombit** [comment]
Works for me with 3.5.0. I'm not sure if Python 3.2 is still supported by upstream or not, but I suppose if it can be made to work without adding too many complications it would be good to support 3.2 also.

If any fix is needed it should be inside the functions rather than affecting call sites; remember that test() is effectively a demonstration of what a user's program would look like. If weird type conversions or version checks are required, they should be handled by the library.

**Comment by webmaster128** [comment]
In Python 3.2 and Python 3.3, unhexlify did only support binary input, as stated here

>  Changed in version 3.2: Accept only bytestring or bytearray objects as input.

https://docs.python.org/3.2/library/binascii.html#binascii.unhexlify

Can we fix that in `def hex_decode(buf):`?

Ubuntu 12.04 LTS with Python 3.2 is going to be supported until April 2017.

**Comment by randombit** [comment]
`In Python 3.2 and Python 3.3, unhexlify did only support binary input`

Wow that's quite the wtf. Happily at least with the workaround everything still works with Python 2.7, 3.5 and PyPy 1.6 also. Hopefully that's the only change needed for 3.2

**Comment by webmaster128** [comment]
Thanks for the change, Jack. I'll rebase and see.

**Comment by webmaster128** [comment]
Thanks everyone.
