### ISSUE TITLE
Decrypt with OAEPWithSHA1AndMGF1Padding

### ISSUE THREAD

**Issue by diorahman** [randombit/botan#406]
I need to send an encrypted bytes (using RSA) to a Java app from a C++ one. The Java app expect to  decrypt the bytes using following code:

```java
Security.addProvider(new BouncyCastleProvider());
Cipher cipher = Cipher.getInstance("RSA/NONE/OAEPWithSHA1AndMGF1Padding");
cipher.init(Cipher.DECRYPT_MODE, key);
return cipher.doFinal(encryptedBytes);
```

What should the C++ use?

I tried `PK_Encryptor_EME encryptor(*key, "EME1(SHA1)");` and it failed.

```
javax.crypto.BadPaddingException: data hash wrong
	at org.bouncycastle.jce.provider.JCERSACipher.engineDoFinal(Unknown Source)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
```

Thank you.

http://stackoverflow.com/q/34700031/427014

**Comment by diorahman** [comment]
My bad the issue is in the key
