### ISSUE TITLE
Documentation build broken

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#460]
Mac OS X 10.11.4, Xcode-7.3, python-2.7.11, currently released Sphinx:
```
$ python --version
Python 2.7.11
$ make install
sphinx-build -c ./src/build-data/sphinx -b latex ./doc/manual build/docs/manual
Traceback (most recent call last):
  File "/opt/local/bin/sphinx-build", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3124, in _call_aside
    f(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 663, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 676, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'imagesize' distribution was not found and is required by Sphinx
make: *** [docs] Error 1
$ cat /opt/local/bin/sphinx-build
#!/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
# EASY-INSTALL-ENTRY-SCRIPT: 'Sphinx==1.4','console_scripts','sphinx-build'
__requires__ = 'Sphinx==1.4'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('Sphinx==1.4', 'console_scripts', 'sphinx-build')()
    )
$
```

**Comment by mouse07410** [comment]
The main problem was in my installation, but something seems wrong with the docs as well:
```
$ cat /var/folders/pd/mxn5kp_55jg23x7jjd10gtwm0000gn/T/sphinx-err-6Jx8Ru.log
# Sphinx version: 1.4
# Python version: 2.7.11 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   writing output... [ 57%] mceliece
#   writing output... [ 61%] ocsp
#   writing output... [ 65%] passhash
#   writing output... [ 69%] pbkdf
#   writing output... [ 73%] pubkey
#   writing output... [ 76%] python
#   writing output... [ 80%] rng
#   writing output... [ 84%] secmem
#   writing output... [ 88%] srp
#   writing output... [ 92%] tls
# Loaded extensions:
#   sphinx.ext.extlinks (1.4) from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/ext/extlinks.pyc
#   alabaster (0.7.7) from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/alabaster/__init__.pyc
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 366, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/environment.py", line 1242, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/environment.py", line 1497, in resolve_references
    typ, target, node, contnode)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/domains/cpp.py", line 4070, in resolve_xref
    target, node, contnode)[0]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/domains/cpp.py", line 4039, in _resolve_xref_inner
    assert parentSymbol  # should be there
AssertionError
$
```

**Comment by mouse07410** [comment]
This bug is being worked on by the Sphinx team: https://github.com/sphinx-doc/sphinx/issues/2413

**Comment by mouse07410** [comment]
Sphinx-doc is introducing the *crash* fix, but the underlying problem (according to https://github.com/sphinx-doc/sphinx/issues/2413) is in the "duplicate declaration of `TLS::Session` (doc/manual/tls.rst line 333 and 369)".

It would be nice if you could address this, probably by removing the extra one (I assume it's the one on line 369?).

**Comment by mouse07410** [comment]
Please see PR https://github.com/randombit/botan/pull/474 that addresses this problem. Hope it can be merged soon.

**Comment by HDembinski** [comment]
It seems I am having the same (?) problem in another build of cpp documentation in my project, https://github.com/HDembinski/histogram. I just updated to Sphinx 1.4.1, but I still get this error:

# Sphinx version: 1.4.1
# Python version: 2.7.6 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   writing output... [ 10%] changelog
#   writing output... [ 20%] functions
#   writing output... [ 30%] index
#   writing output... [ 40%] intro
#   writing output... [ 50%] motivation
#   writing output... [ 60%] notes
#   writing output... [ 70%] rationale
#   writing output... [ 80%] references
#   writing output... [ 90%] tutorial
#   writing output... [100%] types
# Loaded extensions:
#   sphinx.ext.mathjax (1.4.1) from /home/hdembinski/.local/lib/python2.7/site-packages/sphinx/ext/mathjax.pyc
#   sphinx.ext.autodoc (1.4.1) from /home/hdembinski/.local/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.githubpages (1.4.1) from /home/hdembinski/.local/lib/python2.7/site-packages/sphinx/ext/githubpages.pyc
#   alabaster (0.7.7) from /home/hdembinski/.local/lib/python2.7/site-packages/alabaster/__init__.pyc
Traceback (most recent call last):
  File "/home/hdembinski/.local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/hdembinski/.local/lib/python2.7/site-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/home/hdembinski/.local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/hdembinski/.local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/hdembinski/.local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/home/hdembinski/.local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 366, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/home/hdembinski/.local/lib/python2.7/site-packages/sphinx/environment.py", line 1242, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/home/hdembinski/.local/lib/python2.7/site-packages/sphinx/environment.py", line 1497, in resolve_references
    typ, target, node, contnode)
  File "/home/hdembinski/.local/lib/python2.7/site-packages/sphinx/domains/cpp.py", line 4143, in resolve_xref
    target, node, contnode)[0]
  File "/home/hdembinski/.local/lib/python2.7/site-packages/sphinx/domains/cpp.py", line 4112, in _resolve_xref_inner
    assert parentSymbol  # should be there
AssertionError

**Comment by HDembinski** [comment]
At least in my case, the bug is related to the :cpp:namespace: directive. I have this namespace structure

namespace boost {
namespace histogram {
class histogram;
}
}

In the code that was producing the bug, I was using :cpp:namespace:: boost::histogram and then somewhat later :cpp:namespace-push histogram (to document member functions inside the class histogram). After a certain number of member functions added in this way, the crash occured.

My work-around is to drop the first :cpp:namespace:: boost::histogram directive. This makes the crash disappear.
