### ISSUE TITLE
ARMv8/Aarch32 and "error: unable to emulate ‘TI’"

### ISSUE THREAD

**Issue by noloader** [randombit/botan#563]
I testing Master on  on a Raspberry Pi 3. Its ARMv8 with Broadcom SoC using A53 cores. It lacks PMULL{2} and Crypto extensions, but it includes VMULL and CRC32 (VMULL includes arrangements other than u8). The gadget also runs Raspian, which is a 32-bit OS with hard floats. This is a somewhat unique configuration, and the Raspberry folks probably won't support a true Aarch64 gadget. See [ARM NEON programming quick reference](http://community.arm.com/groups/android-community/blog/2015/03/27/arm-neon-programming-quick-reference) for more reading on Aarch32.

Using an ARMv8/Aarch32 configuration for the device results in:

```
g++  -pthread -fstack-protector -march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -march=armv8-a -Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -c ./src/lib/mac/poly1305/poly1305.cpp -o build/obj/lib/mac_poly1305.o
In file included from ./src/lib/mac/poly1305/poly1305.cpp:13:0:
build/include/botan/mul128.h:18:59: error: unable to emulate ‘TI’
    typedef unsigned int uint128_t __attribute__((mode(TI)));
                                                           ^
build/include/botan/mul128.h: In function ‘void Botan::mul64x64_128(Botan::u64bit, Botan::u64bit, Botan::u64bit*, Botan::u64bit*)’:
build/include/botan/mul128.h:31:19: warning: right shift count >= width of type
       *hi = (r >> 64) & 0xFFFFFFFFFFFFFFFF;  \
                   ^
build/include/botan/mul128.h:84:4: note: in expansion of macro ‘BOTAN_FAST_64X64_MUL’
    BOTAN_FAST_64X64_MUL(a, b, lo, hi);
    ^
Makefile:801: recipe for target 'build/obj/lib/mac_poly1305.o' failed
make: *** [build/obj/lib/mac_poly1305.o] Error 1
```

-----

And:

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.9.2 (Raspbian 4.9.2-10) 
```

-----

And:

```
$ ./configure.py --cc=gcc --cpu=armv8-a --cc-abi-flags="-march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard"
   INFO: Platform: OS="Linux" machine="armv7l" proc=""
   INFO: Guessing target OS is linux (use --os to set)
   INFO: Canonicalizized CPU target armv8-a to arm64/armv8-a
   INFO: Target is gcc-linux-arm64-armv8-a
   INFO: Skipping, dependency failure - rdrand sessions_sqlite3
   INFO: Skipping, incompatible CPU - aes_ni aes_ssse3 clmul idea_sse2 rdrand_rng rdseed sha1_sse2 threefish_avx2
   INFO: Skipping, incompatible OS - beos_stats cryptoapi_rng darwin_secrandom win32_stats
   INFO: Skipping, only used if needed or requested - dyn_load
   INFO: Skipping, requires external dependency - boost bzip2 lzma openssl pkcs11 sqlite3 tpm zlib
   INFO: Loading modules adler32 aead aes aont asn1 base base64 bcrypt bigint blake2 block blowfish camellia cascade cast cbc cbc_mac ccm cfb chacha chacha20poly1305 cmac codec_filt comb4p compression crc24 crc32 cryptobox ctr curve25519 datastor des dev_random dh dl_algo dl_group dlies dsa eax ec_gfp ec_group ecb ecc_key ecdh ecdsa ecgdsa ecies eckcdsa egd elgamal eme_oaep eme_pkcs1 eme_raw emsa1 emsa_pkcs1 emsa_pssr emsa_raw emsa_x931 entropy fd_unix ffi filters fpe_fe1 gcm gost_28147 gost_3410 gost_3411 has160 hash hash_id hex hkdf hmac hmac_drbg hmac_rng http_util idea if_algo kasumi kdf kdf1 kdf1_iso18033 kdf2 keccak keypair lion locking_allocator mac mars mce mceies md2 md4 md5 mdx_hash mgf1 misty1 mode_pad modes mp noekeon noekeon_simd nr numbertheory ocb ofb oid_lookup openpgp par_hash passhash9 pbes2 pbkdf pbkdf1 pbkdf2 pem pk_pad poly1305 prf_tls prf_x942 proc_walk pubkey rc2 rc4 rc5 rc6 rfc3394 rfc6979 rmd128 rmd160 rng rsa rw safer salsa20 seed serpent serpent_simd sessions_sql sha1 sha2_32 sha2_64 simd siphash siv skein sp800_108 sp800_56c srp6 stream system_rng tea threefish tiger tls tss twofish unix_procs utils whirlpool x509 x919_mac x931_rng xtea xtea_simd xts
   INFO: Assuming CPU is little endian
   INFO: Using symlink to link files into build dir (use --link-method to change)
   INFO: Botan 1.11.31 (unreleased undated) build setup is complete
raspberrypi:botan$ make
g++  -pthread -fstack-protector -march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -march=armv8-a -Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -c ./src/lib/asn1/alg_id.cpp -o build/obj/lib/asn1_alg_id.o
g++  -pthread -fstack-protector -march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -march=armv8-a -Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -c ./src/lib/asn1/asn1_alt_name.cpp -o build/obj/lib/asn1_alt_name.o
...
```

-----

And the preprocessor defines. [`__ARM_32BIT_STATE`](http://www.google.com/search?q="__ARM_32BIT_STATE"+site%3Aarm.com) is particularly important because it [signals Aarch32](http://www.google.com/search?q="__ARM_32BIT_STATE"+site%3Aarm.com). I'm guessing it can be used to guard the problematic code, if needed.

```
$ g++  -pthread -fstack-protector -march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -march=armv8-a -dM -E - </dev/null | sort
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
#define __ACCUM_EPSILON__ 0x1P-15K
#define __ACCUM_FBIT__ 15
#define __ACCUM_IBIT__ 16
#define __ACCUM_MAX__ 0X7FFFFFFFP-15K
#define __ACCUM_MIN__ (-0X1P15K-0X1P15K)
#define __APCS_32__ 1
#define __arm__ 1
#define __ARM_32BIT_STATE 1
#define __ARM_ARCH 8
#define __ARM_ARCH_8A__ 1
#define __ARM_ARCH_EXT_IDIV__ 1
#define __ARM_ARCH_ISA_ARM 1
#define __ARM_ARCH_ISA_THUMB 2
#define __ARM_ARCH_PROFILE 65
#define __ARM_EABI__ 1
#define __ARMEL__ 1
#define __ARM_FEATURE_CLZ 1
#define __ARM_FEATURE_CRYPTO 1
#define __ARM_FEATURE_DSP 1
#define __ARM_FEATURE_FMA 1
#define __ARM_FEATURE_LDREX 15
#define __ARM_FEATURE_QBIT 1
#define __ARM_FEATURE_SAT 1
#define __ARM_FEATURE_SIMD32 1
#define __ARM_FEATURE_UNALIGNED 1
#define __ARM_FP 14
#define __ARM_NEON 1
#define __ARM_NEON__ 1
#define __ARM_NEON_FP 6
#define __ARM_PCS_VFP 1
#define __ARM_SIZEOF_MINIMAL_ENUM 4
#define __ARM_SIZEOF_WCHAR_T 32
#define __ATOMIC_ACQ_REL 4
#define __ATOMIC_ACQUIRE 2
#define __ATOMIC_CONSUME 1
#define __ATOMIC_RELAXED 0
#define __ATOMIC_RELEASE 3
#define __ATOMIC_SEQ_CST 5
#define __BIGGEST_ALIGNMENT__ 8
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __CHAR16_TYPE__ short unsigned int
#define __CHAR32_TYPE__ unsigned int
#define __CHAR_BIT__ 8
#define __CHAR_UNSIGNED__ 1
#define __DA_FBIT__ 31
#define __DA_IBIT__ 32
#define __DBL_DECIMAL_DIG__ 17
#define __DBL_DENORM_MIN__ ((double)4.9406564584124654e-324L)
#define __DBL_DIG__ 15
#define __DBL_EPSILON__ ((double)2.2204460492503131e-16L)
#define __DBL_HAS_DENORM__ 1
#define __DBL_HAS_INFINITY__ 1
#define __DBL_HAS_QUIET_NAN__ 1
#define __DBL_MANT_DIG__ 53
#define __DBL_MAX_10_EXP__ 308
#define __DBL_MAX__ ((double)1.7976931348623157e+308L)
#define __DBL_MAX_EXP__ 1024
#define __DBL_MIN_10_EXP__ (-307)
#define __DBL_MIN__ ((double)2.2250738585072014e-308L)
#define __DBL_MIN_EXP__ (-1021)
#define __DEC128_EPSILON__ 1E-33DL
#define __DEC128_MANT_DIG__ 34
#define __DEC128_MAX__ 9.999999999999999999999999999999999E6144DL
#define __DEC128_MAX_EXP__ 6145
#define __DEC128_MIN__ 1E-6143DL
#define __DEC128_MIN_EXP__ (-6142)
#define __DEC128_SUBNORMAL_MIN__ 0.000000000000000000000000000000001E-6143DL
#define __DEC32_EPSILON__ 1E-6DF
#define __DEC32_MANT_DIG__ 7
#define __DEC32_MAX__ 9.999999E96DF
#define __DEC32_MAX_EXP__ 97
#define __DEC32_MIN__ 1E-95DF
#define __DEC32_MIN_EXP__ (-94)
#define __DEC32_SUBNORMAL_MIN__ 0.000001E-95DF
#define __DEC64_EPSILON__ 1E-15DD
#define __DEC64_MANT_DIG__ 16
#define __DEC64_MAX__ 9.999999999999999E384DD
#define __DEC64_MAX_EXP__ 385
#define __DEC64_MIN__ 1E-383DD
#define __DEC64_MIN_EXP__ (-382)
#define __DEC64_SUBNORMAL_MIN__ 0.000000000000001E-383DD
#define __DEC_EVAL_METHOD__ 2
#define __DECIMAL_DIG__ 17
#define __DQ_FBIT__ 63
#define __DQ_IBIT__ 0
#define __ELF__ 1
#define __FINITE_MATH_ONLY__ 0
#define __FLOAT_WORD_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __FLT_DECIMAL_DIG__ 9
#define __FLT_DENORM_MIN__ 1.4012984643248171e-45F
#define __FLT_DIG__ 6
#define __FLT_EPSILON__ 1.1920928955078125e-7F
#define __FLT_EVAL_METHOD__ 0
#define __FLT_HAS_DENORM__ 1
#define __FLT_HAS_INFINITY__ 1
#define __FLT_HAS_QUIET_NAN__ 1
#define __FLT_MANT_DIG__ 24
#define __FLT_MAX_10_EXP__ 38
#define __FLT_MAX__ 3.4028234663852886e+38F
#define __FLT_MAX_EXP__ 128
#define __FLT_MIN_10_EXP__ (-37)
#define __FLT_MIN__ 1.1754943508222875e-38F
#define __FLT_MIN_EXP__ (-125)
#define __FLT_RADIX__ 2
#define __FP_FAST_FMA 1
#define __FP_FAST_FMAF 1
#define __FP_FAST_FMAL 1
#define __FRACT_EPSILON__ 0x1P-15R
#define __FRACT_FBIT__ 15
#define __FRACT_IBIT__ 0
#define __FRACT_MAX__ 0X7FFFP-15R
#define __FRACT_MIN__ (-0.5R-0.5R)
#define __GCC_ATOMIC_BOOL_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR32_T_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR_LOCK_FREE 2
#define __GCC_ATOMIC_INT_LOCK_FREE 2
#define __GCC_ATOMIC_LLONG_LOCK_FREE 2
#define __GCC_ATOMIC_LONG_LOCK_FREE 2
#define __GCC_ATOMIC_POINTER_LOCK_FREE 2
#define __GCC_ATOMIC_SHORT_LOCK_FREE 2
#define __GCC_ATOMIC_TEST_AND_SET_TRUEVAL 1
#define __GCC_ATOMIC_WCHAR_T_LOCK_FREE 2
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8 1
#define __GCC_IEC_559 2
#define __GCC_IEC_559_COMPLEX 2
#define __GNUC__ 4
#define __GNUC_GNU_INLINE__ 1
#define __GNUC_MINOR__ 9
#define __GNUC_PATCHLEVEL__ 2
#define __gnu_linux__ 1
#define __GXX_ABI_VERSION 1002
#define __GXX_TYPEINFO_EQUALITY_INLINE 0
#define __HA_FBIT__ 7
#define __HA_IBIT__ 8
#define __has_include_next(STR) __has_include_next__(STR)
#define __has_include(STR) __has_include__(STR)
#define __HQ_FBIT__ 15
#define __HQ_IBIT__ 0
#define __INT16_C(c) c
#define __INT16_MAX__ 32767
#define __INT16_TYPE__ short int
#define __INT32_C(c) c
#define __INT32_MAX__ 2147483647
#define __INT32_TYPE__ int
#define __INT64_C(c) c ## LL
#define __INT64_MAX__ 9223372036854775807LL
#define __INT64_TYPE__ long long int
#define __INT8_C(c) c
#define __INT8_MAX__ 127
#define __INT8_TYPE__ signed char
#define __INT_FAST16_MAX__ 2147483647
#define __INT_FAST16_TYPE__ int
#define __INT_FAST32_MAX__ 2147483647
#define __INT_FAST32_TYPE__ int
#define __INT_FAST64_MAX__ 9223372036854775807LL
#define __INT_FAST64_TYPE__ long long int
#define __INT_FAST8_MAX__ 127
#define __INT_FAST8_TYPE__ signed char
#define __INT_LEAST16_MAX__ 32767
#define __INT_LEAST16_TYPE__ short int
#define __INT_LEAST32_MAX__ 2147483647
#define __INT_LEAST32_TYPE__ int
#define __INT_LEAST64_MAX__ 9223372036854775807LL
#define __INT_LEAST64_TYPE__ long long int
#define __INT_LEAST8_MAX__ 127
#define __INT_LEAST8_TYPE__ signed char
#define __INT_MAX__ 2147483647
#define __INTMAX_C(c) c ## LL
#define __INTMAX_MAX__ 9223372036854775807LL
#define __INTMAX_TYPE__ long long int
#define __INTPTR_MAX__ 2147483647
#define __INTPTR_TYPE__ int
#define __LACCUM_EPSILON__ 0x1P-31LK
#define __LACCUM_FBIT__ 31
#define __LACCUM_IBIT__ 32
#define __LACCUM_MAX__ 0X7FFFFFFFFFFFFFFFP-31LK
#define __LACCUM_MIN__ (-0X1P31LK-0X1P31LK)
#define __LDBL_DENORM_MIN__ 4.9406564584124654e-324L
#define __LDBL_DIG__ 15
#define __LDBL_EPSILON__ 2.2204460492503131e-16L
#define __LDBL_HAS_DENORM__ 1
#define __LDBL_HAS_INFINITY__ 1
#define __LDBL_HAS_QUIET_NAN__ 1
#define __LDBL_MANT_DIG__ 53
#define __LDBL_MAX_10_EXP__ 308
#define __LDBL_MAX__ 1.7976931348623157e+308L
#define __LDBL_MAX_EXP__ 1024
#define __LDBL_MIN_10_EXP__ (-307)
#define __LDBL_MIN__ 2.2250738585072014e-308L
#define __LDBL_MIN_EXP__ (-1021)
#define __LFRACT_EPSILON__ 0x1P-31LR
#define __LFRACT_FBIT__ 31
#define __LFRACT_IBIT__ 0
#define __LFRACT_MAX__ 0X7FFFFFFFP-31LR
#define __LFRACT_MIN__ (-0.5LR-0.5LR)
#define __linux 1
#define __linux__ 1
#define linux 1
#define __LLACCUM_EPSILON__ 0x1P-31LLK
#define __LLACCUM_FBIT__ 31
#define __LLACCUM_IBIT__ 32
#define __LLACCUM_MAX__ 0X7FFFFFFFFFFFFFFFP-31LLK
#define __LLACCUM_MIN__ (-0X1P31LLK-0X1P31LLK)
#define __LLFRACT_EPSILON__ 0x1P-63LLR
#define __LLFRACT_FBIT__ 63
#define __LLFRACT_IBIT__ 0
#define __LLFRACT_MAX__ 0X7FFFFFFFFFFFFFFFP-63LLR
#define __LLFRACT_MIN__ (-0.5LLR-0.5LLR)
#define __LONG_LONG_MAX__ 9223372036854775807LL
#define __LONG_MAX__ 2147483647L
#define __OPTIMIZE__ 1
#define __ORDER_BIG_ENDIAN__ 4321
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_PDP_ENDIAN__ 3412
#define __pic__ 2
#define __PIC__ 2
#define __PRAGMA_REDEFINE_EXTNAME 1
#define __PTRDIFF_MAX__ 2147483647
#define __PTRDIFF_TYPE__ int
#define __QQ_FBIT__ 7
#define __QQ_IBIT__ 0
#define _REENTRANT 1
#define __REGISTER_PREFIX__ 
#define __SACCUM_EPSILON__ 0x1P-7HK
#define __SACCUM_FBIT__ 7
#define __SACCUM_IBIT__ 8
#define __SACCUM_MAX__ 0X7FFFP-7HK
#define __SACCUM_MIN__ (-0X1P7HK-0X1P7HK)
#define __SA_FBIT__ 15
#define __SA_IBIT__ 16
#define __SCHAR_MAX__ 127
#define __SFRACT_EPSILON__ 0x1P-7HR
#define __SFRACT_FBIT__ 7
#define __SFRACT_IBIT__ 0
#define __SFRACT_MAX__ 0X7FP-7HR
#define __SFRACT_MIN__ (-0.5HR-0.5HR)
#define __SHRT_MAX__ 32767
#define __SIG_ATOMIC_MAX__ 2147483647
#define __SIG_ATOMIC_MIN__ (-__SIG_ATOMIC_MAX__ - 1)
#define __SIG_ATOMIC_TYPE__ int
#define __SIZE_MAX__ 4294967295U
#define __SIZEOF_DOUBLE__ 8
#define __SIZEOF_FLOAT__ 4
#define __SIZEOF_INT__ 4
#define __SIZEOF_LONG__ 4
#define __SIZEOF_LONG_DOUBLE__ 8
#define __SIZEOF_LONG_LONG__ 8
#define __SIZEOF_POINTER__ 4
#define __SIZEOF_PTRDIFF_T__ 4
#define __SIZEOF_SHORT__ 2
#define __SIZEOF_SIZE_T__ 4
#define __SIZEOF_WCHAR_T__ 4
#define __SIZEOF_WINT_T__ 4
#define __SIZE_TYPE__ unsigned int
#define __SQ_FBIT__ 31
#define __SQ_IBIT__ 0
#define __SSP__ 1
#define __STDC__ 1
#define __STDC_HOSTED__ 1
#define __STDC_IEC_559__ 1
#define __STDC_IEC_559_COMPLEX__ 1
#define __STDC_ISO_10646__ 201103L
#define __STDC_NO_THREADS__ 1
#define _STDC_PREDEF_H 1
#define __TA_FBIT__ 63
#define __TA_IBIT__ 64
#define __THUMB_INTERWORK__ 1
#define __TQ_FBIT__ 127
#define __TQ_IBIT__ 0
#define __UACCUM_EPSILON__ 0x1P-16UK
#define __UACCUM_FBIT__ 16
#define __UACCUM_IBIT__ 16
#define __UACCUM_MAX__ 0XFFFFFFFFP-16UK
#define __UACCUM_MIN__ 0.0UK
#define __UDA_FBIT__ 32
#define __UDA_IBIT__ 32
#define __UDQ_FBIT__ 64
#define __UDQ_IBIT__ 0
#define __UFRACT_EPSILON__ 0x1P-16UR
#define __UFRACT_FBIT__ 16
#define __UFRACT_IBIT__ 0
#define __UFRACT_MAX__ 0XFFFFP-16UR
#define __UFRACT_MIN__ 0.0UR
#define __UHA_FBIT__ 8
#define __UHA_IBIT__ 8
#define __UHQ_FBIT__ 16
#define __UHQ_IBIT__ 0
#define __UINT16_C(c) c
#define __UINT16_MAX__ 65535
#define __UINT16_TYPE__ short unsigned int
#define __UINT32_C(c) c ## U
#define __UINT32_MAX__ 4294967295U
#define __UINT32_TYPE__ unsigned int
#define __UINT64_C(c) c ## ULL
#define __UINT64_MAX__ 18446744073709551615ULL
#define __UINT64_TYPE__ long long unsigned int
#define __UINT8_C(c) c
#define __UINT8_MAX__ 255
#define __UINT8_TYPE__ unsigned char
#define __UINT_FAST16_MAX__ 4294967295U
#define __UINT_FAST16_TYPE__ unsigned int
#define __UINT_FAST32_MAX__ 4294967295U
#define __UINT_FAST32_TYPE__ unsigned int
#define __UINT_FAST64_MAX__ 18446744073709551615ULL
#define __UINT_FAST64_TYPE__ long long unsigned int
#define __UINT_FAST8_MAX__ 255
#define __UINT_FAST8_TYPE__ unsigned char
#define __UINT_LEAST16_MAX__ 65535
#define __UINT_LEAST16_TYPE__ short unsigned int
#define __UINT_LEAST32_MAX__ 4294967295U
#define __UINT_LEAST32_TYPE__ unsigned int
#define __UINT_LEAST64_MAX__ 18446744073709551615ULL
#define __UINT_LEAST64_TYPE__ long long unsigned int
#define __UINT_LEAST8_MAX__ 255
#define __UINT_LEAST8_TYPE__ unsigned char
#define __UINTMAX_C(c) c ## ULL
#define __UINTMAX_MAX__ 18446744073709551615ULL
#define __UINTMAX_TYPE__ long long unsigned int
#define __UINTPTR_MAX__ 4294967295U
#define __UINTPTR_TYPE__ unsigned int
#define __ULACCUM_EPSILON__ 0x1P-32ULK
#define __ULACCUM_FBIT__ 32
#define __ULACCUM_IBIT__ 32
#define __ULACCUM_MAX__ 0XFFFFFFFFFFFFFFFFP-32ULK
#define __ULACCUM_MIN__ 0.0ULK
#define __ULFRACT_EPSILON__ 0x1P-32ULR
#define __ULFRACT_FBIT__ 32
#define __ULFRACT_IBIT__ 0
#define __ULFRACT_MAX__ 0XFFFFFFFFP-32ULR
#define __ULFRACT_MIN__ 0.0ULR
#define __ULLACCUM_EPSILON__ 0x1P-32ULLK
#define __ULLACCUM_FBIT__ 32
#define __ULLACCUM_IBIT__ 32
#define __ULLACCUM_MAX__ 0XFFFFFFFFFFFFFFFFP-32ULLK
#define __ULLACCUM_MIN__ 0.0ULLK
#define __ULLFRACT_EPSILON__ 0x1P-64ULLR
#define __ULLFRACT_FBIT__ 64
#define __ULLFRACT_IBIT__ 0
#define __ULLFRACT_MAX__ 0XFFFFFFFFFFFFFFFFP-64ULLR
#define __ULLFRACT_MIN__ 0.0ULLR
#define __unix 1
#define __unix__ 1
#define unix 1
#define __UQQ_FBIT__ 8
#define __UQQ_IBIT__ 0
#define __USACCUM_EPSILON__ 0x1P-8UHK
#define __USACCUM_FBIT__ 8
#define __USACCUM_IBIT__ 8
#define __USACCUM_MAX__ 0XFFFFP-8UHK
#define __USACCUM_MIN__ 0.0UHK
#define __USA_FBIT__ 16
#define __USA_IBIT__ 16
#define __USER_LABEL_PREFIX__ 
#define __USFRACT_EPSILON__ 0x1P-8UHR
#define __USFRACT_FBIT__ 8
#define __USFRACT_IBIT__ 0
#define __USFRACT_MAX__ 0XFFP-8UHR
#define __USFRACT_MIN__ 0.0UHR
#define __USQ_FBIT__ 32
#define __USQ_IBIT__ 0
#define __UTA_FBIT__ 64
#define __UTA_IBIT__ 64
#define __UTQ_FBIT__ 128
#define __UTQ_IBIT__ 0
#define __VERSION__ "4.9.2"
#define __VFP_FP__ 1
#define __WCHAR_MAX__ 4294967295U
#define __WCHAR_MIN__ 0U
#define __WCHAR_TYPE__ unsigned int
#define __WINT_MAX__ 4294967295U
#define __WINT_MIN__ 0U
#define __WINT_TYPE__ unsigned int
```

**Comment by randombit** [comment]
The code is assuming that if the processor itself is 64-bit then a native 128-bit type must be available via TI mode. I imagine the same issue would arise on SPARCv9 or MIPS64 with a 32-bit userland. Probably using either TI mode or `__int128` should be guarded by `defined(__SIZEOF_INT128__)` (currently only `__int128` is), with TI mode preferred for GCC to avoid -Wpedantic warnings.

**Comment by noloader** [comment]
Looks good, close it. I'll open another issue if `botan_test` has a problem.

-----

```
...
g++  -pthread -fstack-protector -march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8
-mfloat-abi=hard -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -march=armv8-a
-Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations
-Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include
-c ./src/lib/mac/poly1305/poly1305.cpp -o build/obj/lib/mac_poly1305.o

g++  -pthread -fstack-protector -march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8
-mfloat-abi=hard -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -march=armv8-a
-Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations
-Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include
-c ./src/lib/mac/siphash/siphash.cpp -o build/obj/lib/mac_siphash.o
...
```

**Comment by randombit** [comment]
It would be nice to characterize this crash better, it may well be a compiler problem, but botan is made of code and code sometimes has bugs. Is this reproducible and if so can you post a backtrace?

**Comment by noloader** [comment]
Botan was configured with:

```
$ ./configure.py --cc=gcc --cpu=armv8-a --cc-abi-flags="-march=armv8-a+crc
    -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard -g3 -O1"
```

I built GDB 7.11.1 from sources in an attempt to gt something usful. GDB's tip has a few problems, and I have not received the gdb bug tracker notifications that the issues have been fixed.

```
DLIES ran 144 tests in 211.06 sec all ok
DLIES XOR ran 12 tests all ok
[New Thread 0x76899450 (LWP 6384)]
pure virtual method called
terminate called without an active exception

Thread 2 "botan-test" received signal SIGABRT, Aborted.
[Switching to Thread 0x76899450 (LWP 6384)]
0x768d8f70 in raise () from /lib/arm-linux-gnueabihf/libc.so.6
(gdb) bt full
#0  0x768d8f70 in raise () from /lib/arm-linux-gnueabihf/libc.so.6
No symbol table info available.
#1  0x768da324 in abort () from /lib/arm-linux-gnueabihf/libc.so.6
No symbol table info available.
#2  0x00000020 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by noloader** [comment]
@randombit,

I don't feel good about this bug report remaining open. There's a few of reasons.

First, the original issue was resolved. Second, RPI3 tools, like the compiler and debugger, have a number of problems. Third, the RPI3 hardware has some known issues, and it [locks ups several times a day](https://www.google.com/search?q=rpi3+lock+up).

The tools and the lockups are unique to the RPI3. I have 8 IoT ARM gadgets I test under, and this is the only platform I see the problem.

All-in-all, I would recommend closing this until it can be duplicated on device that does not lock-up, or until the tools catch-up with the platform.

**Comment by randombit** [comment]
Fair enough, closing.
