### ISSUE TITLE
"nmake install" fails 

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#85]
Hi,

`nmake install` fails with following output:

```
nmake install

Microsoft (R) Program Maintenance Utility, Version 12.00.21005.1
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

        copy doc\manual\*.rst build\docs\manual
doc\manual\aead.rst
doc\manual\bigint.rst
doc\manual\building.rst
doc\manual\contents.rst
doc\manual\credentials_manager.rst
doc\manual\cryptobox.rst
doc\manual\ffi.rst
doc\manual\filters.rst
doc\manual\firststep.rst
doc\manual\fpe.rst
doc\manual\index.rst
doc\manual\kdf.rst
doc\manual\lowlevel.rst
doc\manual\ocsp.rst
doc\manual\passhash.rst
doc\manual\pbkdf.rst
doc\manual\pubkey.rst
doc\manual\python.rst
doc\manual\rng.rst
doc\manual\secmem.rst
doc\manual\srp.rst
doc\manual\tls.rst
doc\manual\versions.rst
doc\manual\x509.rst
       24 Datei(en) kopiert.
        src\scripts\install.py --destdir=c:\Botan --bindir=bin --libdir=lib --docdir=docs --includedir=include
  ERROR: Failure: [Errno 2] No such file or directory: 'botan-1.11.lib'
   INFO: Traceback (most recent call last):
  File "C:\devel\botan\src\scripts\install.py", line 204, in <module>
    sys.exit(main())
  File "C:\devel\botan\src\scripts\install.py", line 145, in main
    copy_file(static_lib, os.path.join(lib_dir, os.path.basename(static_lib)))
  File "C:\devel\botan\src\scripts\install.py", line 94, in copy_file
    shutil.copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'botan-1.11.lib'

NMAKE : fatal error U1077: "src\scripts\install.py": Rückgabe-Code "0x1"
Stop.
```

The issue here is that the library name is "botan.lib" on Windows and the install script assumes it to be "botan-1.11.lib".

I've already tried to adjust the libname in `nmake.in` but msvc is somehow ignoring everything after a dot. This results in an output of "botan-1.lib"

**Comment by webmaster128** [comment]
Did you see that `LIBNAME` is defines twice in a `Makefile` for nmake on Windows? (which is another topic …). I think the desired output filename is `botan.lib`, so the error must be in the install.py script.

**Comment by webmaster128** [comment]
@neusdan Could you verify whether #110 solves the issue in your environment?

**Comment by neusdan** [comment]
Hi,

yes, now its working. nice work. thanks.
